version: '3'
services:
  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - fullstack

  db:
    image: mariadb:10.5.10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: database
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - fullstack

  app:
    container_name: golang-example-app
    build: .
    ports:
      - 3030:8080
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - fullstack

volumes:
  db-data:

networks:
  fullstack:
    driver: bridge
