CREATE TABLE IF NOT EXISTS user_meta (
    id INT NOT NULL AUTO_INCREMENT,
    meta_key VARCHAR(255) NOT NULL,
    meta_value VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;